name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .  # Installs the package and its dependencies from setup.py
        pip install pytest

    - name: Run tests with pytest
      run: pytest

  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build package
      run: python -m build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/

  pypi-publish:
    name: Upload release to PyPI
    needs: [test, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/matplobblib
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/